/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Route */
        post: operations["login_route_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout Route */
        post: operations["logout_route_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me Route */
        get: operations["me_route_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password Route */
        post: operations["change_password_route_api_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["list_audit_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Packages Route
         * @description Fleet-wide aggregate: one row per package name. Default landing view.
         */
        get: operations["list_packages_route_api_inventory_packages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/packages/{name}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Versions Route
         * @description All distinct versions of one named package, with per-version minion counts.
         */
        get: operations["list_versions_route_api_inventory_packages__name__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/packages/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Packages Route
         * @description Row-level package search. Used by level 3 (minions with one specific
         *     name+version) and as a power-user query endpoint (version comparison,
         *     multi-field filter).
         */
        post: operations["search_packages_route_api_inventory_packages_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Route */
        post: operations["refresh_route_api_inventory_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs Route */
        get: operations["list_jobs_route_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs Activity Route */
        get: operations["jobs_activity_route_api_jobs_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{jid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Route */
        get: operations["get_job_route_api_jobs__jid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{jid}/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kill Job Route */
        post: operations["kill_job_route_api_jobs__jid__kill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Keys Route */
        get: operations["list_keys_route_api_keys_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{key_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Key Route */
        post: operations["accept_key_route_api_keys__key_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{key_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Key Route */
        post: operations["reject_key_route_api_keys__key_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Key Route */
        delete: operations["delete_key_route_api_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/minions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Minions Route */
        get: operations["list_minions_route_api_minions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/minions/{minion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Minion Route */
        get: operations["get_minion_route_api_minions__minion_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roles Route */
        get: operations["list_roles_route_api_roles_get"];
        put?: never;
        /** Create Role Route */
        post: operations["create_role_route_api_roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Role Route */
        get: operations["get_role_route_api_roles__role_id__get"];
        put?: never;
        post?: never;
        /** Delete Role Route */
        delete: operations["delete_role_route_api_roles__role_id__delete"];
        options?: never;
        head?: never;
        /** Update Role Route */
        patch: operations["update_role_route_api_roles__role_id__patch"];
        trace?: never;
    };
    "/api/roles/{role_id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Permission Route */
        post: operations["add_permission_route_api_roles__role_id__permissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{role_id}/permissions/{permission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Permission Route */
        delete: operations["remove_permission_route_api_roles__role_id__permissions__permission_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Command Route */
        post: operations["run_command_route_api_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/salt/functions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Functions Route
         * @description List the names of execution functions the salt master knows about.
         *
         *     Requires authentication (any logged-in user). Cached for 1 hour to
         *     avoid hammering salt-api on every page render.
         */
        get: operations["list_functions_route_api_salt_functions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users Route */
        get: operations["list_users_route_api_users_get"];
        put?: never;
        /** Create User Route */
        post: operations["create_user_route_api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Route */
        get: operations["get_user_route_api_users__user_id__get"];
        put?: never;
        post?: never;
        /** Delete User Route */
        delete: operations["delete_user_route_api_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User Route */
        patch: operations["update_user_route_api_users__user_id__patch"];
        trace?: never;
    };
    "/api/users/{user_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password Route */
        post: operations["reset_password_route_api_users__user_id__password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List User Roles Route */
        get: operations["list_user_roles_route_api_users__user_id__roles_get"];
        put?: never;
        /** Add User Role Route */
        post: operations["add_user_role_route_api_users__user_id__roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove User Role Route */
        delete: operations["remove_user_role_route_api_users__user_id__roles__role_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEntryOut */
        AuditEntryOut: {
            /** Id */
            id: number;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** User Id */
            user_id: string | null;
            /** Action */
            action: string;
            /** Resource */
            resource: string;
            /** Args Json */
            args_json: Record<string, never> | null;
            /** Salt Jid */
            salt_jid: string | null;
            /** Decision */
            decision: string;
            /** Result Code */
            result_code: number;
            /** Duration Ms */
            duration_ms: number;
        };
        /** AuditListOut */
        AuditListOut: {
            /** Total */
            total: number;
            /** Entries */
            entries: components["schemas"]["AuditEntryOut"][];
        };
        /** ChangePasswordPayload */
        ChangePasswordPayload: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobActivityBucket */
        JobActivityBucket: {
            /** Hour Start */
            hour_start: string;
            /** Count */
            count: number;
        };
        /** JobActivityOut */
        JobActivityOut: {
            /** Hours */
            hours: number;
            /** Buckets */
            buckets: components["schemas"]["JobActivityBucket"][];
            /** Total */
            total: number;
            /** Running */
            running: number;
        };
        /** JobDetail */
        JobDetail: {
            /** Jid */
            jid: string;
            /** Function */
            function: string;
            /**
             * Arguments
             * @default []
             */
            arguments: unknown[];
            /** Kwargs */
            kwargs?: {
                [key: string]: unknown;
            };
            /** Target */
            target: string;
            /** Target Type */
            target_type?: string | null;
            /** User */
            user?: string | null;
            /** Start Time */
            start_time?: string | null;
            /**
             * Minions
             * @default []
             */
            minions: string[];
            /**
             * Results
             * @default []
             */
            results: components["schemas"]["JobMinionResult"][];
        };
        /** JobMinionResult */
        JobMinionResult: {
            /** Minion */
            minion: string;
            /** Success */
            success?: boolean | null;
            /** Retcode */
            retcode?: number | null;
            /** Return Value */
            return_value?: unknown;
        };
        /** JobSummary */
        JobSummary: {
            /** Jid */
            jid: string;
            /** Function */
            function: string;
            /** Target */
            target: string;
            /** Target Type */
            target_type?: string | null;
            /** User */
            user?: string | null;
            /** Start Time */
            start_time?: string | null;
            /**
             * Status
             * @default complete
             * @enum {string}
             */
            status: "running" | "complete";
        };
        /** JobsListOut */
        JobsListOut: {
            /** Total */
            total: number;
            /** Jobs */
            jobs: components["schemas"]["JobSummary"][];
        };
        /** KeyEntry */
        KeyEntry: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "pending" | "rejected" | "denied";
        };
        /** KeysListOut */
        KeysListOut: {
            /** Total */
            total: number;
            /** Keys */
            keys: components["schemas"]["KeyEntry"][];
        };
        /** LoginPayload */
        LoginPayload: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MinionDetail */
        MinionDetail: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "online" | "offline" | "pending" | "rejected" | "denied";
            /** Ip */
            ip?: string | null;
            /** Grains */
            grains?: Record<string, never> | null;
        };
        /** MinionListOut */
        MinionListOut: {
            /** Total */
            total: number;
            /** Minions */
            minions: components["schemas"]["MinionSummary"][];
        };
        /** MinionSummary */
        MinionSummary: {
            /** Id */
            id: string;
            /** Ip */
            ip?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "online" | "offline" | "pending" | "rejected" | "denied";
        };
        /**
         * NameFilter
         * @description A name-side filter. ``op="eq"`` becomes ``name = ?``;
         *     ``op="prefix"`` becomes ``name LIKE ? || '%'`` (cheap, hits the index);
         *     ``op="contains"`` becomes ``name LIKE '%' || ? || '%'`` (slower, full scan
         *     of the (name)-indexed range but acceptable at our fleet size).
         */
        NameFilter: {
            /**
             * Op
             * @default eq
             * @enum {string}
             */
            op: "eq" | "prefix" | "contains";
            /** Value */
            value: string;
        };
        /**
         * PackageAggregate
         * @description One row in the fleet-wide package list.
         */
        PackageAggregate: {
            /** Name */
            name: string;
            /** Minion Count */
            minion_count: number;
            /** Version Count */
            version_count: number;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
        };
        /** PackageAggregateOut */
        PackageAggregateOut: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["PackageAggregate"][];
        };
        /**
         * PackageQueryHit
         * @description One row in the response to a package query.
         */
        PackageQueryHit: {
            /** Minion Id */
            minion_id: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Arch */
            arch?: string | null;
            /** Source */
            source?: string | null;
            /**
             * Collected At
             * Format: date-time
             */
            collected_at: string;
        };
        /**
         * PackageQueryIn
         * @description Filter for ``GET /api/inventory/packages``.
         *
         *     At least one of ``name`` or ``minion_id`` MUST be supplied — we don't
         *     want to accidentally let the UI fetch the entire fleet's package list
         *     in one request. (A future "browse all" endpoint can lift this rule.)
         */
        PackageQueryIn: {
            name?: components["schemas"]["NameFilter"] | null;
            version?: components["schemas"]["VersionFilter"] | null;
            /** Source */
            source?: ("apt" | "rpm" | "pacman") | null;
            /** Minion Id */
            minion_id?: string | null;
            /**
             * Limit
             * @default 500
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /**
         * PackageQueryOut
         * @description Wrapper that lets us tack pagination metadata on later without breaking
         *     the wire format.
         */
        PackageQueryOut: {
            /** Total */
            total: number;
            /** Hits */
            hits: components["schemas"]["PackageQueryHit"][];
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** PasswordResetPayload */
        PasswordResetPayload: {
            /** New Password */
            new_password: string;
            /**
             * Must Change Pw
             * @default true
             */
            must_change_pw: boolean;
        };
        /** PermissionOut */
        PermissionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Verb */
            verb: string;
            /** Resource Glob */
            resource_glob: string;
        };
        /** PermissionPair */
        PermissionPair: {
            /** Verb */
            verb: string;
            /** Resource Glob */
            resource_glob: string;
        };
        /** PermissionPayload */
        PermissionPayload: {
            /** Verb */
            verb: string;
            /** Resource Glob */
            resource_glob: string;
        };
        /**
         * RefreshIn
         * @description Body for ``POST /api/inventory/refresh``.
         *
         *     ``target='*'`` + ``target_type='glob'`` means "every connected minion".
         *     Pin the target down if you want to refresh just one host.
         */
        RefreshIn: {
            /**
             * Target
             * @default *
             */
            target: string;
            /**
             * Target Type
             * @default glob
             * @enum {string}
             */
            target_type: "glob" | "list" | "pcre" | "grain" | "nodegroup" | "compound";
        };
        /** RefreshOut */
        RefreshOut: {
            /** Minions Refreshed */
            minions_refreshed: number;
            /** Package Counts */
            package_counts: {
                [key: string]: number;
            };
        };
        /** RoleAssignmentPayload */
        RoleAssignmentPayload: {
            /**
             * Role Id
             * Format: uuid
             */
            role_id: string;
        };
        /** RoleCreatePayload */
        RoleCreatePayload: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** RoleDetail */
        RoleDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Is Builtin */
            is_builtin: boolean;
            /** Description */
            description: string;
            /** Permissions */
            permissions: components["schemas"]["PermissionOut"][];
        };
        /** RoleListOut */
        RoleListOut: {
            /** Total */
            total: number;
            /** Roles */
            roles: components["schemas"]["RoleSummary"][];
        };
        /** RoleSummary */
        RoleSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Is Builtin */
            is_builtin: boolean;
            /** Description */
            description: string;
        };
        /** RoleUpdatePayload */
        RoleUpdatePayload: {
            /** Description */
            description?: string | null;
        };
        /** RunCommandIn */
        RunCommandIn: {
            /** Target */
            target: string;
            /**
             * Target Type
             * @default glob
             * @enum {string}
             */
            target_type: "glob" | "list" | "pcre" | "grain" | "nodegroup" | "compound";
            /** Fun */
            fun: string;
            /**
             * Args
             * @default []
             */
            args: string[];
            /** Kwargs */
            kwargs?: {
                [key: string]: unknown;
            };
        };
        /** RunCommandOut */
        RunCommandOut: {
            /** Jid */
            jid: string;
            /** Minions */
            minions: string[];
        };
        /** SaltFunctionsOut */
        SaltFunctionsOut: {
            /** Functions */
            functions: string[];
            /**
             * Cached At
             * Format: date-time
             */
            cached_at: string;
        };
        /** UserCreatePayload */
        UserCreatePayload: {
            /** Username */
            username: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /** Email */
            email?: string | null;
            /** Password */
            password: string;
            /**
             * Must Change Pw
             * @default true
             */
            must_change_pw: boolean;
            /** Role Ids */
            role_ids?: string[];
        };
        /** UserListOut */
        UserListOut: {
            /** Total */
            total: number;
            /** Users */
            users: components["schemas"]["UserSummary"][];
        };
        /** UserOut */
        UserOut: {
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Must Change Pw */
            must_change_pw: boolean;
            /**
             * Permissions
             * @default []
             */
            permissions: components["schemas"]["PermissionPair"][];
        };
        /** UserSummary */
        UserSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string | null;
            /** Is Active */
            is_active: boolean;
            /** Is Builtin */
            is_builtin: boolean;
            /** Must Change Pw */
            must_change_pw: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login At */
            last_login_at: string | null;
        };
        /** UserUpdatePayload */
        UserUpdatePayload: {
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionAggregate
         * @description One row in the per-package version list.
         */
        VersionAggregate: {
            /** Version */
            version: string;
            /** Arch */
            arch?: string | null;
            /** Source */
            source?: string | null;
            /** Minion Count */
            minion_count: number;
        };
        /** VersionAggregateOut */
        VersionAggregateOut: {
            /** Name */
            name: string;
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["VersionAggregate"][];
        };
        /**
         * VersionFilter
         * @description A version comparison applied per-row in Python after SQL narrowing.
         */
        VersionFilter: {
            /**
             * Op
             * @enum {string}
             */
            op: "eq" | "ne" | "lt" | "lte" | "gt" | "gte";
            /** Value */
            value: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    login_route_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_route_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_route_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    change_password_route_api_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_api_audit_get: {
        parameters: {
            query?: {
                user_id?: string | null;
                action?: string | null;
                decision?: string | null;
                since?: string | null;
                until?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_packages_route_api_inventory_packages_get: {
        parameters: {
            query?: {
                q?: string | null;
                source?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageAggregateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_route_api_inventory_packages__name__versions_get: {
        parameters: {
            query?: {
                source?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionAggregateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_packages_route_api_inventory_packages_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageQueryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageQueryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_route_api_inventory_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_route_api_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jobs_activity_route_api_jobs_activity_get: {
        parameters: {
            query?: {
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobActivityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_route_api_jobs__jid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kill_job_route_api_jobs__jid__kill_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_keys_route_api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeysListOut"];
                };
            };
        };
    };
    accept_key_route_api_keys__key_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_key_route_api_keys__key_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_key_route_api_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_minions_route_api_minions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinionListOut"];
                };
            };
        };
    };
    get_minion_route_api_minions__minion_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                minion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_route_api_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleListOut"];
                };
            };
        };
    };
    create_role_route_api_roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreatePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_role_route_api_roles__role_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_role_route_api_roles__role_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_role_route_api_roles__role_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdatePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_permission_route_api_roles__role_id__permissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermissionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_permission_route_api_roles__role_id__permissions__permission_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
                permission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_command_route_api_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCommandIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCommandOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_functions_route_api_salt_functions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaltFunctionsOut"];
                };
            };
        };
    };
    list_users_route_api_users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_route_api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreatePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_route_api_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_route_api_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_route_api_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdatePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_route_api_users__user_id__password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_user_roles_route_api_users__user_id__roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_user_role_route_api_users__user_id__roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleAssignmentPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_user_role_route_api_users__user_id__roles__role_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                role_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
